import{dateKey,weekStart,parseGoal,detect,weeklyReport}from"./lib/productivity.js";
const KEY="daymark-private-v1",today=dateKey(),week=dateKey(weekStart());
let state=load();rollover();ensureDay();save();
const $=s=>document.querySelector(s),els={goals:$("#goals"),today:$("#today-tasks"),tomorrow:$("#tomorrow"),done:$("#done-input"),recognized:$("#recognized"),modal:$("#modal"),body:$("#modal-body")};
$("#date").textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric"}).format(new Date());$("#week").textContent=`Week of ${new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(weekStart())}`;els.done.value=state.days[today].note;
$("#goal-form").addEventListener("submit",e=>{e.preventDefault();const g=parseGoal($("#goal-input").value);if(!g.text)return;state.goals.push({id:crypto.randomUUID(),...g,done:false});$("#goal-input").value="";persist()});
$("#tomorrow-form").addEventListener("submit",e=>{e.preventDefault();const text=$("#tomorrow-input").value.trim();if(!text)return;state.tomorrow.push(task(text));$("#tomorrow-input").value="";persist()});
els.done.addEventListener("input",()=>{state.days[today].note=els.done.value;save();renderDetected()});
$("#log-button").addEventListener("click",()=>{const day=state.days[today],found=detect(els.done.value,day.tasks,state.goals);found.goals=found.goals.filter(g=>!day.goalCredits.includes(g.id));found.tasks.forEach(t=>{t.done=true;t.completedAt=Date.now()});found.goals.forEach(g=>{g.target===null?g.done=true:g.current=Math.min(g.target,g.current+1);day.goalCredits.push(g.id)});day.loggedAt=Date.now();persist();toast(found.tasks.length+found.goals.length?`Updated ${found.tasks.length+found.goals.length} items`:"Reflection saved")});
$("#report-button").addEventListener("click",showReport);$("#privacy-button").addEventListener("click",showPrivacy);$("#history-button").addEventListener("click",showHistory);$(".close").addEventListener("click",()=>els.modal.close());
function load(){try{return{version:1,currentWeek:week,lastOpen:today,goals:[],tomorrow:[],days:{},...JSON.parse(localStorage.getItem(KEY))}}catch{return{version:1,currentWeek:week,lastOpen:today,goals:[],tomorrow:[],days:{}}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function task(text){return{id:crypto.randomUUID(),text,done:false,completedAt:null}}
function ensureDay(){if(!state.days[today]){state.days[today]={date:today,tasks:state.tomorrow.map(t=>task(t.text)),note:"",loggedAt:null,goalCredits:[]};state.tomorrow=[]}state.days[today].goalCredits=state.days[today].goalCredits||[]}
function rollover(){if(state.currentWeek!==week){state.weekArchive=state.weekArchive||[];state.weekArchive.push({week:state.currentWeek,goals:state.goals,lockedAt:Date.now()});state.goals=state.goals.filter(g=>g.target!==null&&g.current<g.target).map(g=>({...g,current:0,done:false}));state.currentWeek=week}state.lastOpen=today}
function persist(){save();render()}
function row(item,kind){const done=kind==="goal"?(item.target===null?item.done:item.current>=item.target):item.done;const el=document.createElement("div");el.className=`item${done?" done":""}`;el.innerHTML=`<button class="check">${done?"✓":""}</button><div class="copy"></div><button class="remove">×</button>`;el.querySelector(".copy").textContent=item.target===null||kind!=="goal"?item.text:`${item.text} ${item.current}/${item.target}`;if(kind==="goal"&&item.target!==null)el.querySelector(".copy").insertAdjacentHTML("beforeend",`<div class="meter"><i style="width:${Math.min(100,item.current/item.target*100)}%"></i></div>`);el.querySelector(".check").onclick=()=>{if(kind==="goal"){item.target===null?item.done=!item.done:item.current=item.current>=item.target?0:item.target}else{item.done=!item.done;item.completedAt=item.done?Date.now():null}persist()};el.querySelector(".remove").onclick=()=>{const list=kind==="goal"?state.goals:kind==="today"?state.days[today].tasks:state.tomorrow;list.splice(list.findIndex(x=>x.id===item.id),1);persist()};return el}
function fill(container,list,kind,message){container.innerHTML="";if(!list.length)container.innerHTML=`<p class="empty">${message}</p>`;else list.forEach(x=>container.append(row(x,kind)))}
function render(){fill(els.goals,state.goals,"goal","What would make this week count?");fill(els.today,state.days[today].tasks,"today","No plan carried over. Your reflection still counts.");fill(els.tomorrow,state.tomorrow,"tomorrow","Leave tomorrow a useful starting point.");const done=state.days[today].tasks.filter(t=>t.done).length;$("#today-score").textContent=`${done} of ${state.days[today].tasks.length}`;const pct=state.goals.length?Math.round(state.goals.reduce((n,g)=>n+(g.target?g.current/g.target:+g.done),0)/state.goals.length*100):0;$("#goal-score").textContent=$("#goals-stat").textContent=`${pct}%`;const days=Object.values(state.days).filter(d=>d.date>=week);$("#completed-stat").textContent=days.flatMap(d=>d.tasks).filter(t=>t.done).length;$("#days-stat").textContent=days.filter(d=>d.note.trim()||d.tasks.some(t=>t.done)).length;renderDetected()}
function renderDetected(){const day=state.days[today],f=detect(els.done.value,day.tasks,state.goals);f.goals=f.goals.filter(g=>!day.goalCredits.includes(g.id));const names=[...f.tasks,...f.goals].map(x=>x.text);els.recognized.textContent=names.length?`✦ Recognized: ${names.join(", ")}`:"✦ Matching tasks and habits will appear here."}
function modal(kicker,title,html){$("#modal-kicker").textContent=kicker;$("#modal-title").textContent=title;els.body.innerHTML=html;els.modal.showModal()}
function showReport(){modal("Generated locally","Weekly report",`<textarea readonly></textarea><div class="actions"><button id="copy">Copy report</button><button class="quiet" id="export">Export private data</button></div>`);els.body.querySelector("textarea").value=weeklyReport(state);$("#copy").onclick=async()=>{await navigator.clipboard.writeText(weeklyReport(state));toast("Report copied")};$("#export").onclick=exportData}
function showPrivacy(){modal("Privacy by design","Your data stays yours",`<p>Daymark has no account, analytics, server, database, or built-in email provider. Notes are stored only in this browser on this device.</p><p>Export a JSON file when you want your own Codex setup to create or email a report. Your Codex credentials and email connection never pass through Daymark.</p><div class="actions"><button id="export">Export data</button><button class="quiet" id="import">Import backup</button><input id="file" type="file" accept=".json" hidden></div>`);$("#export").onclick=exportData;$("#import").onclick=()=>$("#file").click();$("#file").onchange=importData}
function showHistory(){const days=Object.values(state.days).sort((a,b)=>b.date.localeCompare(a.date));modal("Stored on this device","History",days.length?days.map(d=>`<article class="history"><h3>${d.date}</h3><p>${d.tasks.filter(t=>t.done).map(t=>t.text).join(", ")||"No completed tasks"}</p><p>${d.note||"No reflection"}</p>${d.date!==today?`<button class="quiet late" data-date="${d.date}">Edit late log</button>`:""}</article>`).join(""):"<p>No history yet.</p>");els.body.querySelectorAll(".late").forEach(b=>b.onclick=()=>{const d=state.days[b.dataset.date],value=prompt(`Reflection for ${d.date}`,d.note);if(value!==null){d.note=value;save();showHistory()}})}
function exportData(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download=`daymark-${today}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(e){const reader=new FileReader();reader.onload=()=>{try{state=JSON.parse(reader.result);ensureDay();persist();els.modal.close();toast("Backup imported")}catch{toast("That file is not a Daymark backup")}};reader.readAsText(e.target.files[0])}
function toast(text){const t=$("#toast");t.textContent=text;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),1700)}
render();
