const ignored=new Set(["a","an","and","at","did","do","for","get","got","i","in","it","my","of","on","the","to","was","went","with"]);
const aliases={groceries:"grocery",grocery:"grocery",workout:"gym",exercise:"gym",exercised:"gym",finished:"finish",completed:"complete"};
export function dateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
export function weekStart(date=new Date()){const d=new Date(date);d.setDate(d.getDate()-d.getDay());d.setHours(0,0,0,0);return d}
export function parseGoal(value){const match=value.trim().match(/^(.*?)\s+(\d+)\s*\/\s*(\d+)(?:\s+days?)?$/i);return match?{text:match[1],current:+match[2],target:+match[3]}:{text:value.trim(),current:null,target:null}}
function words(value){return value.toLowerCase().replace(/[^a-z0-9\s]/g," ").split(/\s+/).filter(w=>w.length>1&&!ignored.has(w)).map(w=>aliases[w]||w.replace(/(ing|ed|es|s)$/,""))}
export function matches(text,label){const source=new Set(words(text));const target=words(label.replace(/\d+\s*\/\s*\d+/,""));const hits=target.filter(word=>source.has(word)).length;return target.length>0&&(hits>=Math.min(2,target.length)||hits/target.length>=.6)}
export function detect(text,tasks,goals){return{tasks:tasks.filter(t=>!t.done&&matches(text,t.text)),goals:goals.filter(g=>(g.target===null?!g.done:g.current<g.target)&&matches(text,g.text))}}
export function weeklyReport(state,now=new Date()){const start=dateKey(weekStart(now));const endDate=weekStart(now);endDate.setDate(endDate.getDate()+6);const end=dateKey(endDate);const days=Object.values(state.days).filter(d=>d.date>=start&&d.date<=end).sort((a,b)=>a.date.localeCompare(b.date));const tasks=days.flatMap(d=>d.tasks.filter(t=>t.done));const active=days.filter(d=>d.note.trim()||d.tasks.some(t=>t.done));const goals=state.goals.length?state.goals.map(g=>`- ${g.text}: ${g.target===null?(g.done?"complete":"open"):`${g.current}/${g.target}`}`):["- No weekly goals recorded."];const notes=days.filter(d=>d.note.trim()).map(d=>`- ${d.date}: ${d.note.trim()}`);return["DAYMARK WEEKLY REPORT",`${start} to ${end}`,"","SUMMARY",`${tasks.length} tasks completed across ${active.length} active day${active.length===1?"":"s"}.`,"","WEEKLY GOALS",...goals,"","COMPLETED",...(tasks.length?tasks.map(t=>`- ${t.text}`):["- Nothing logged yet."]),"","DAILY NOTES",...(notes.length?notes:["- No reflections recorded."]),"","PATTERN TO NOTICE",active.length>=5?"You recorded consistent activity across most of the week.":`You recorded activity on ${active.length} day${active.length===1?"":"s"}. A smaller daily plan may make consistency easier.`,"","NEXT WEEK","- Carry forward only goals that still matter.","- Choose one outcome that would make the week successful."].join("\n")}
